### ISSUE TITLE
Where can I find ontology related RDF data?

### ISSUE THREAD

**Issue by k00ni** [Project-Haystack/haystack-defs#17]
I am interested in the RDF part of your project, but having a hard time locating the RDF data of the ontology. There is some talk about ontologies in the documentation, such as https://project-haystack.org/doc/docHaystack/Ontology or https://project-haystack.org/doc/docHaystack/Defs, so I assume you provide an OWL ontology somehow. And I've also manage to find https://project-haystack.org/download/defs.ttl on the download page (https://project-haystack.org/download), but it doesn't contain an instance of `owl:Ontology`.

Does `defs.ttl` contains all parts of the ontology or is there something else?

Thanks for your feedback in advance.

**Comment by briansfrank** [comment]
There is not an owl ontology.  There is a RDF file that uses parts of OWL which you have pointed out, but it has some problems for inference engines.  There is a project to redefine it using SHACL (not  OWL).
