### ISSUE TITLE
Why is phenomenon "air" missing?

### ISSUE THREAD

**Issue by Dunken** [Project-Haystack/haystack-defs#21]
Can anybody explain why the phenomenon "air" is missing in this proto? Seems inconsistent with other protos (e.g., when I check the AHU protos hierarchy).

https://github.com/Project-Haystack/haystack-defs/blob/8de71edfb3496da634ac3fc117585cb28d73ce50/src/docHaystack/doc/Motors.fandoc#L87

**Comment by briansfrank** [comment]
Typically air tag is used for sensor/setpoints related to air measurements.  Fan points are associated with control of the actual fan equipment, not air measurements.  But many people put air tag on their tag points, it doesn't hurt anything.  So none of the Haystack 3 protots include that tag.  However, I did put air on the fan specs for Xeto:

https://github.com/Project-Haystack/xeto/blob/master/src/xeto/ph.points/fan.xeto

I think it could go either way myself if you want to post on forum to get opinions

**Comment by Benedikt-Schumacher** [comment]
Is there a concept behind that in the case of "chilled water" phenomenon this tag gets applied to all sort of points whereas in the case of "air" it is only used for sensors an setpoints?

**Comment by Benedikt-Schumacher** [comment]
Would it be possible to apply for all points a phenomenon (or even two if its a data point on intersections where two phenomenons come together like heat exchangers, e.g. chilled water and air) in order to support filtering for "air" and finding all air related data points in a building. Or what would be the preferred phenomenon for a point on a fan?

**Comment by briansfrank** [comment]
You really need to ask these questions on the forum where the community does its communications:

https://project-haystack.org/forum/topic
